"""Unique constraints and indexes

Revision ID: ea566b5493e5
Revises: f3897e90455a
Create Date: 2023-12-18 16:00:07.059375

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea566b5493e5"
down_revision: Union[str, None] = "f3897e90455a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("plays_UQ1", "plays", ["game_id", "ingame_play_id"])
    op.create_unique_constraint("tackles_UQ1", "tackles", ["play_id", "player_id"])
    op.create_index(op.f("ix_tracking_play_id"), "tracking", ["play_id"], unique=False)
    op.create_unique_constraint(
        "tracking_UQ1", "tracking", ["play_id", "player_id", "frame"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tracking_UQ1", "tracking", type_="unique")
    op.drop_index(op.f("ix_tracking_play_id"), table_name="tracking")
    op.drop_constraint("tackles_UQ1", "tackles", type_="unique")
    op.drop_constraint("plays_UQ1", "plays", type_="unique")
    # ### end Alembic commands ###
