"""tracking_team_relationship

Revision ID: ef800797cc6c
Revises: ea566b5493e5
Create Date: 2023-12-30 00:50:01.175859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef800797cc6c'
down_revision: Union[str, None] = 'ea566b5493e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracking', 'teams', ['team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking', type_='foreignkey')
    op.drop_column('tracking', 'team_id')
    # ### end Alembic commands ###
